GET     http://localhost:3000/users/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvZ2VAZW1haWwuY29tIiwicGFzc3dvcmQiOiJob2dlIiwiaWF0IjoxNTIwODc0OTY1LCJleHAiOjE1MjA4Nzg1NjV9.UGLbxl3IG12-KOi_XOrhV6Y7SMuILP7YswBekeigJPU

