GET     http://localhost:3000/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvZ2VAZW1haWwuY29tIiwicGFzc3dvcmQiOiJob2dlIiwiaWF0IjoxNTE5NzcxOTAyLCJleHAiOjE1MTk3NzU1MDJ9.-J3iUADY48pbZuWku2mqU3RoaCNAmki0qozHHN9DL2U

