GET     http://localhost:3000/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAdGVzdC5jb20iLCJwYXNzd29yZCI6ImEiLCJpYXQiOjE1MjA5NzYzODIsImV4cCI6MTUyMDk3OTk4Mn0.p2iwBCL1pBQFYe3CDRi_8h1nE7YTjCi--aiLTcUUo1g

